### ISSUE TITLE
struct in interface

### ISSUE THREAD

**Issue by ar-mokhtari** [ar-mokhtari/tel-note#2]
```go
type storageMemory struct {
	CityData []*protocol.City
	PoolByID map[uint]*protocol.City
}

var (
	storage storageMemory
	//TODO::: What does this do?
	_ protocol.CityServices = &storage
)
```

**Comment by OmidHekayati** [comment]
`_ protocol.CityServices = &storage` just check `storageMemory` struct implements needed methods (APIs) to respect protocol.CityServices interface.

**Comment by ar-mokhtari** [comment]
1. Its interested to equal “struct" and "interface" with "=" 
2. Also, Its interested when I didn't respect to interface, I got error with this line, and it's good to notice ...
