### ISSUE TITLE
What is better way to check if struct element is nil, ignore to edit

### ISSUE THREAD

**Issue by ar-mokhtari** [ar-mokhtari/tel-note#3]
```go
func (allCity *storageMemory) EditCity(ID uint, newCity protocol.City) bool {
	for index, data := range allCity.CityData {
		if data.Id == ID {
			//TODO:: what the hell below ... is there any cleaner way for test "is it not nil?"
			if newCity.Name != "" {
				(allCity.CityData)[index].Name = newCity.Name
			}
			if newCity.EnglishName != "" {
				(allCity.CityData)[index].EnglishName = newCity.EnglishName
			}
			if newCity.AriaCode != "" {
				(allCity.CityData)[index].AriaCode = newCity.AriaCode
			}
			if newCity.Lat != 0.0 {
				(allCity.CityData)[index].Lat = newCity.Lat
			}
			if newCity.Lng != 0.0 {
				(allCity.CityData)[index].Lng = newCity.Lng
			}
			return true
		}
	}
	return false
}

```

**Comment by OmidHekayati** [comment]
I think `newCity.Name != ""` is business logic and can't write in another way.
I just have a suggestion for you. if most time `EditCity` is successful to update data, let the compiler make better machine code in this way:
```go
func (sm *storageMemory) EditCity(ID uint, newCity protocol.City) (err error) {
  var exitingCity = sm.GetCity(ID)
  if exitingCity == nil {
    // err = TODO:::
    return
  }

  var newCityName = newCity.Name
  if newCityName != "" {
    // TODO::: first remove last index
    (allCity.CityData)[index].Name = newCityName
  }
  // TODO::: add more logic
  return
}

func (sm *storageMemory) GetCity(ID uint) (city protocol.City) {
  for index, data := range allCity.CityData {
    if data.Id == ID {
      city = data
      break
    }
  }
  return
}
```

**Comment by ar-mokhtari** [comment]
this is changes:
func (sm *storageMemory) EditCity(newCity protocol.City) (err error) {
	var index, exitingCity = sm.GetCity(newCity.Id)
	// check for found city
	if (protocol.City{}) == exitingCity {
		return errors.New("not found")
	}
	// try to edit
	if newCity.Name != "" {
		(sm.CityData)[index].Name = newCity.Name
	}
	if newCity.EnglishName != "" {
		(sm.CityData)[index].EnglishName = newCity.EnglishName
	}
	if newCity.AriaCode != "" {
		(sm.CityData)[index].AriaCode = newCity.AriaCode
	}
	if newCity.Lat != 0.0 {
		(sm.CityData)[index].Lat = newCity.Lat
	}
	if newCity.Lng != 0.0 {
		(sm.CityData)[index].Lng = newCity.Lng
	}
	return nil
}

func (sm *storageMemory) GetCity(ID uint) (cityIndex int, city protocol.City) {
	for index, data := range sm.CityData {
		if data.Id == ID {
			return index, *data
		}
	}
	return -1, protocol.City{}
}

**Comment by ar-mokhtari** [comment]
> ```go
>   if exitingCity == nil {
>     // err = TODO:::
>     return
>   }
> ```

```go
 if exitingCity == nil {
```
has error ... replaced by 
```go
if (protocol.City{}) == exitingCity {
```
Though we have <<index>> that if variable of struct return nil, is -1
